DROP TABLE IF EXISTS `real_data_rec`;
CREATE TABLE `real_data_rec` (
	`ID` INT(11) NOT NULL COMMENT 'ID',
	`AUTH_CODE_CDE` VARCHAR(50) NOT NULL COMMENT 'AUTH_CODE',
	`IP_ADDR` VARCHAR(50) NOT NULL COMMENT 'USER_IP',
	`CUST_ID` INT(11) NULL DEFAULT NULL COMMENT 'CUSTOM_ID',
	`PROD_ID` INT(11) NULL DEFAULT NULL COMMENT 'PROD_ID',
	`REAL_DETEM` VARCHAR(2) NULL DEFAULT NULL COMMENT 'REAL ANS',
	`SYS_DETEM` VARCHAR(2) NULL DEFAULT NULL COMMENT 'SYSTEM RETURN',
	`REF_STATE` VARCHAR(2) NULL DEFAULT NULL COMMENT 'REFERNCE STATE ;R:Real Date,E:Extended Data',
	`PUR_DT` TIMESTAMP NULL DEFAULT NULL COMMENT 'PURCHASE DATETIME',
	`ACT_DT` TIMESTAMP NULL DEFAULT NULL COMMENT 'USERER QUERY DATETIME',
	`QUES_DT` TIMESTAMP NULL DEFAULT NULL COMMENT 'QUESTION DATETIME',
	`CHECK_STATE` VARCHAR(10) NULL DEFAULT NULL COMMENT 'Y:CONFIRMED',
	`REMARK` VARCHAR(250) NULL DEFAULT NULL COMMENT '',
	PRIMARY KEY (`ID`),
	INDEX `AUTH_CODE_CDE` (`AUTH_CODE_CDE`),
	INDEX `ACT_DT` (`ACT_DT`),
	INDEX `IP_ADDR` (`IP_ADDR`)
)
COLLATE='utf8_general_ci'
ENGINE=InnoDB
;
